Trace plot update
bumps/bumps pull request #170
Opened 2024-10-03 21:20 UTC by hoogerheide

Fresh version of https://github.com/bumps/bumps/pull/168

Update to the parameter trace plot. Major changes:

1. Plot is now rendered in plotly
2. Any fittable parameter can be selected for inspection.
3. Colors has been moved from refl1d to bumps

An open question:
At the moment the parameter trace plot is using uncertainty_state, and it updates with the "updated_uncertainty" signal. It is not clear to me if the information in this plot can be updated more regularly; a more natural update signal would be "updated_convergence", but of course at the moment the uncertainty state isn't updated with the convergence updates so this doesn't really make sense.

2024-10-03 21:42 UTC, bmaranville commented
The "updated_uncertainty" signal is sent every time the fit thread sends a new copy of the uncertainty state to the server, so you can't really access it faster than that from the client.

On the other hand, it has been planned for quite some time to expose the uncertainty update time as a user parameter in the fit options panel, it's just yet another thing we haven't gotten to yet!

If you could set that to something shorter than the current 300 seconds, I think that might address your issue.

2024-10-04 13:38 UTC, hoogerheide commented
This is probably fine. I guess logp is being sent back in "real time", which would be the information used in the convergence plot. I can't really imagine anybody sitting and watching the trace plot -- it's probably not more useful than setting the update uncertainty timer to 60 seconds or so, which is what you suggested. Let's not worry about this and just leave it as updating with the uncertainty.

I *do* like the idea of allowing the uncertainty state to be updated, at a different rate from the autosave interval, during fits.

2024-10-16 18:13 UTC, bmaranville requested changes
Looks good overall, but I think it might be a lot cleaner to move the whole plot implementation to traceplot.py (taking the uncertainty state as an argument)

2024-10-16 18:13 UTC, bmaranville commented on bumps/webview/server/api.py
> +             np.squeeze(points[start:, uncertainty_state._good_chains, var]).T, label=label, alpha=0.4)
What is `np.squeeze` doing in this context?

2024-10-16 18:13 UTC, bmaranville commented on bumps/webview/server/api.py
> +async def get_parameter_trace_plot(var: int):
Would it make sense to define a function `get_parameter_trace_plot(uncertainty_state: MCMCDraw, var_index: int=0)` in `traceplot.py`, instead of defining it here, since you're already splitting off a smaller part of the plot implementation there?

2024-10-16 20:23 UTC, hoogerheide commented on bumps/webview/server/api.py
> +             np.squeeze(points[start:, uncertainty_state._good_chains, var]).T, label=label, alpha=0.4)
It removes the extra dimension from `points`. The last dimension of `points` has length Nvar, but this dimension persists when selecting the parameter with index `var`. `np.squeeze` gets rid of the extra dimension.

2024-10-16 20:40 UTC, bmaranville commented on bumps/webview/server/api.py
> +async def get_parameter_trace_plot(var: int):
That's fair - I agree with separating the plotting-library-specific code off.

2024-10-16 20:41 UTC, bmaranville approved these changes

2024-10-16 20:42 UTC, bmaranville commented
Is the colors change already merged in bumps?

2024-10-16 20:43 UTC, merged